### ISSUE TITLE
erreur dans les tests info 121 de paris sud

### ISSUE THREAD

**Issue by HuxoD142** [PremierLangage/conceptexo#20]
Bonsoir,

Comme je l'ai expliqué dans la première issue que j'ai fermé après avoir trouvé mon erreur, j'essaye de faire fonctionner le builder de Nicolas. Cette fois je me retrouve face à une erreur que je ne sais pas du tout comment corriger. la trace est ci-dessous. On peut aussi retrouver l'activité à l'adresse suivante : https://pl-preprod.u-pem.fr/playexo/activity/41/ 

Je pense que c'est encore un fichier que je n'ai pas importé correctement car quelque-soit le text que j'entre dans le formulaire j'ai la même erreur.

Merci pour l'aide

Cordialement
Hugo Mlodecki

____________

Execution of the evaluating script failed due to an unkwown error. Please contact your teacher.
Sandbox error:

An unknown error occured:
Traceback (most recent call last):
  File "/srv/local/pl/pl-sandbox/sandbox/executor.py", line 102, in get_context
    with open(os.path.join(self.cw.envpath, PROCESSED_CONTEXT_FILE)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/srv/local/pl/pl-sandbox/containers_env/c4/processed.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/local/pl/pl-sandbox/sandbox/executor.py", line 235, in execute
    "context":    self.get_context() if not exit_code else {},
  File "/srv/local/pl/pl-sandbox/sandbox/executor.py", line 106, in get_context
    raise ContextNotFoundError
sandbox.exceptions.ContextNotFoundError

Received on stderr:

**Comment by qcoumes** [comment]
Bonsoir,

Merci pour ce retour, l'erreur ne provient pas de vous mais de la dernière version de la sandbox (en test sur pl-preprod). Elle attends forcément un context modifié après une évaluation, alors que celui-ci devrait être facultatif.
Je vais voir pour corriger ça demain matin.

Cordialement,
Quentin Coumes

**Comment by qcoumes** [comment]
Le bug devrait maintenant être corrigé, je vous laisse confirmer.

**Comment by HuxoD142** [comment]
En effet, cela marche bien !
Merci !
