### ISSUE TITLE
Paris-sud Exam la semaine prochaine plus une question

### ISSUE THREAD

**Issue by HuxoD142** [PremierLangage/conceptexo#22]
Bonjour,

Nous (avec @nthiery @hivert) prévoyons de faire un petit exam la semaine prochaine à Paris sud avec Premier langage. Nous souhaitons savoir si nous pouvons utiliser le serveur preprod pour cela. De plus pour les notes, Nicolas m'a dit que c'était à vous que je devais demander après coup, comment cela se passe exactement ?

J'ai aussi une autre question sur l'editeur de text. Je n'arrive pas à faire en sorte que le code entré par l'etudiant soit conservé après validation. Je sais que vous le faite et j'aimerais comprendre comment. Peut-être est-il possible de s'appeler pour en parler plus directement ?

Cordialement
Hugo Mlodecki

**Comment by nimdanor** [comment]
Ok

preprod fonctionne nous avons un problème sur la prod.

Mais nous ne toucherons pas à la préprod pour la semaine prochaine,

je le signal à @pavel9000 et @qcoumes.

Cordialement




Le 21/02/2019 à 13:46, HuxoD142 a écrit :

**Comment by HuxoD142** [comment]
Super,

Florent, Nicolas et moi vous en remercions !

Hugo Mlodecki

**Comment by hivert** [comment]
Excellent ! Merci !

**Comment by HuxoD142** [comment]
Bonjour,

Vous ne m'avez pas répondu pour les notes, comment je pourrais les récupérer ?

Hugo

**Comment by qcoumes** [comment]
Bonjour,

Il faudra me communiquer l'ID de la classe (visible dans l'URL), ainsi que l'ID de l'activité (pareil), ainsi qu'une date à partir de laquel faire l'extraction des notes.

Quentin

**Comment by HuxoD142** [comment]
Rebonjour,

Pour faire en sorte de cacher la fiche aux étudiants une fois le contrôle fini, comment je dois faire ?
Si je reload une autre fiche avec le même numéro d'activité cela marche-t-il ? Dans ce cas la, les notes sont-elles bien sauvegarder ?

Hugo

**Comment by nthiery** [comment]
>    Pour faire en sorte de cacher la fiche aux étudiants une fois le
>    contrôle fini, comment je dois faire ?

Je ne crois pas qu'il y ait quelque chose de prévu au niveau PL pour
le moment. Fait le juste au niveau de moodle.

**Comment by qcoumes** [comment]
Bonjour,

> J'ai aussi une autre question sur l'editeur de text. Je n'arrive pas à faire en sorte que le code entré par l'etudiant soit conservé après validation. Je sais que vous le faite et j'aimerais comprendre comment. Peut-être est-il possible de s'appeler pour en parler plus directement ?

L'éditeur de texte `/lib/form/text_editor.html` conserve normalement le code après la validation.

Si vous souhaites implémenter un éditeur, voici comment faire:

Les réponses de l'élèves sont disponible dans le dictionnaire `answers__`, où chaque réponse est associé à l'id du formulaire (sans le préfixe `form_`).

Par exemple, pour un formulaire:
```html
<input id="form_answer" type="text" class="form-control" required/>
<input id="form_another_answer" type="text" class="form-control" required/>
```
Si l'élève réponds respectivement "réponse 1" et "réponse2", ce dictionnaire `answers__` sera crée:
```python
{
    "answer": "réponse 1"
    "another_answer": "réponse 2"
}
```

Il suffit donc de mettre ces réponses au tag `value`, des *inputs* (sachant que si une variable n'existe pas, elle sera remplacé par la chaine vide):
```html
<input id="form_answer" type="text" class="form-control" value="{{ answers__.answer }} required/>
<input id="form_another_answer" type="text" class="form-control" value="{{ answers__.another_answer }} required/>
```

Dans le cas d'une réponse par défaut (un bout de code par exemple), il est possible d'utilisé le filtre `firstof`, utilisant la première variable existante de la liste des variable donné.

Par exemple, en supposant que `default_answer` contient une réponse par défaut:
```html
<input id="form_answer" type="text" class="form-control" value="{% firstof answers__.answer default_answer %} required/>
```

`default_answer ` sera donc utilisé tant que `answers__.answer` n'existe pas.

**Comment by qcoumes** [comment]
Bonjour,

Pourriez-vous m'indiquer combien d'étudiant y aura-t-il d'élève (approximativement) lors de l'examen ?

Quentin

**Comment by HuxoD142** [comment]
Bonjour,

Il y aura environ 400 étudiants en tout répartis sur 3 jours.
max 200 le mercredi matin de 10h30 à 11h
max 50   le jeudi matin de 10h30 à 11h
max 50   le vendredi matin de 8h15 à 8h45
max 200 le vendredi matin de 10h30 à 11h

Hugo

**Comment by HuxoD142** [comment]
Bonjour,

Toujours par rapport au contrôle de cette semaine, je ne sais pas si le gradder fonctionne bien car tous les exercices restent "jaune" qu'ils soient réussi ou non. Il me semble qu'a un moment les exercices devenaient "vert" une fois que la bonne réponse était trouvé.
Par exemple dans le résumé de l'activité suivante :
https://pl-preprod.u-pem.fr/courses/course/3/64/summary/
Pour vérifier, je voudrais savoir si les notes qui sont déjà dans la base de données ont un sens. Par exemple pour l'activité ci-dessus (numéro 64 pour le cours Info 121 MPI)

Hugo

**Comment by qcoumes** [comment]
Bonjour,

Les notes semblent cohérentes, si vous me fournissez une adresse mail, je peux vous les envoyer si vous le souhaitez.


Quentin

**Comment by Pavell94000** [comment]
Bonjour,

Nous avons également de déployé une mise à jour sur pl-preprod qui corrige le bug de la couleur. (Un bouton suivant est également présent lorsqu'un exercice est réussi)

Christophe

**Comment by HuxoD142** [comment]
Super, je vois les couleurs, j'imagine que le gradder fonctionne comme il faut alors !
Voici mon adresse mail : hugo.mlodecki@gmail.com

**Comment by HuxoD142** [comment]
Bonjour,

Avec 200 étudiants en même temps le temps de réponse était beaucoup trop long, nous avons du abandonner l'idée de devoir en temps impartie et avont donner la fiche de contrôle à faire en devoir. Je voulais vous tenir imformé.

Hugo

**Comment by HuxoD142** [comment]
Bonjour,

Nous souhaiterons retenter l'experience en Avril pour un contrôle en temps limité. Qu'elles sont les mesures à prendre de nos deux coté pour que cela fonctionne ? Les effectifs serons similaire :

> Il y aura environ 400 étudiants en tout répartis sur 3 jours.
> max 200 le mercredi matin de 10h30 à 11h
> max 50 le jeudi matin de 10h30 à 11h
> max 50 le vendredi matin de 8h15 à 8h45
> max 200 le vendredi matin de 10h30 à 11h

Cordialement
Hugo

**Comment by qcoumes** [comment]
Bonjour,

Si nous résolvons le problème du serveur de la sandbox d'ici là, il ne devrait y avoir aucune mesure à prendre de votre coté. En revanche cet examen devra plutôt être tenté sur pl.u-pem.fr plutot que sur pl-reprod.u-pem.fr.

Quentin

**Comment by nthiery** [comment]
Thanks Quentin for [your support](#issuecomment-466507496). For now we did not find a way to reuse (pieces of) the standard editor, so we for now we duplicate it and adapt. With your hints, the inputs are now preserved, as desired.

https://github.com/PremierLangage/cpp-info111/issues/5

**Comment by nthiery** [comment]
Closing this issue since the other question was answered as well. Thanks for the support!
